name: Continous deployment
# will run job only when main & production push and when PR
on:
  pull_request:
  push:
    branches:
      - main
      - production
jobs:
  Test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run Tests
        # setup project to run tests with docker compose
        # run: docker-compose run --rm app sh -c "test"
        run: echo "RUNNING TEST"

  Lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Lint Check
        # setup project to run lint with docker compose
        # run: docker-compose run --rm app sh -c "test"
        run: echo "RUNNING LINT /"

  Validate-terraform:
    name: Terraform validation
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Terraform Validate
        run: echo "validate terraform"

  Build-push:
    name: Build and push image
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/production'
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Build and push
        run: echo "Build and push code here /"

  Staging-plan:
    name: Staging plan
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/production'
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Staging plan
        run: echo "Run terraform PLAN for staging-PLAN /"

  Staging-apply:
    name: Staging apply
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/production'
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Staging Apply
        run: echo "Run terraform APPLY for staging-apply /"

  Production-plan:
    name: Production-plan
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/production'
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Build and push
        run: echo "Run terraform PLAN for production-plan /"

  Production-apply:
    name: Production-apply
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/production'
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Build and push
        run: echo "Run terraform APPLY for production-apply /"
