name: Continous deployment
# will run job only when main & production push and when PR
# define an image we need for terraform job

on:
  pull_request:
  push:
    branches:
      - main
      - production

jobs:
  Terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: hashicorp/terraform
          # options: -v ${{ github.workspace }}:/var/www
          run: |
            cd deploy/
            terraform init -backend=false
            terraform fmt -check

      # - name: Setup Terraform
      #   uses: hashicorp/terraform
      # - name: Terraform init
      #   run: |
      #     cd deploy
      #     terraform init -backend=false
      #     terraform fmt -check

  Test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run Tests
        # setup project to run tests with docker compose
        # run: docker-compose run --rm app sh -c "test"
        run: echo "RUNNING TEST"

  Lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Lint Check
        # setup project to run lint with docker compose
        # run: docker-compose run --rm app sh -c "test"
        run: echo "RUNNING LINT /"

  Validate-terraform:
    name: Terraform validation
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Terraform Validate
        run: echo "validate terraform"

  Build-push:
    name: Build and push image
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/production'
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Build and push
        run: echo "Build and push code here /"
